### ISSUE TITLE
Issues with angular-material

### ISSUE THREAD

**Issue by asm0dey** [nobitagit/ng-material-floating-button#11] opened 2015-03-22 06:22 UTC
Hello!

I'm not good enough in css, but there are some problems in work of this component together with angular-material.
In triggered state it looks like this:
![_012](https://cloud.githubusercontent.com/assets/1297282/6768300/61ca26dc-d074-11e4-904e-d66cba5750a9.png)

And in not triggered:
![_013](https://cloud.githubusercontent.com/assets/1297282/6768305/b3d28bf4-d074-11e4-9bfd-f7cdddd47ff8.png)

As you can see here is 2 issues:

* Icon is on the top of the button, not in center
* Menu item has no icon at all

My code:
```html
<nav mfb-menu position="br" effect="zoomin" label="hover here" active-icon="ion-edit" resting-icon="ion-plus-round"  toggling-method="hover">
    <a mfb-button icon="paper-airplane" label="text here"></a>
</nav>
```
Looks like code from example for me.

**Comment by nobitagit** [comment] 2015-03-22 12:10
Hi there.
I tested the demo adding the styles and scripts taken from [here](https://github.com/angular/material) and could not recreate the issue you are reporting.

Have you tried removing all your own styles and see if the problem is still there?
Does removing the angular material css solve the issue?
Can you please share an example for me to look at otherwise it's very hard to see which part of the css is causing the issue.

Closing for now, but will surely reopen in case the issue is confirmed. 
Thanks for reporting, let me know if you can share a plunkr or a fiddle.

**Closed by nobitagit** 2015-03-22 12:10 UTC

**Comment by asm0dey** [comment] 2015-03-22 19:17
You can see demo here:
http://46.28.202.209:8081/

login with admin/admin

**Comment by asm0dey** [comment] 2015-03-22 19:25
No, removing any of css doesn't help. But I'm not able to understand where is problem...

**Comment by asm0dey** [comment] 2015-03-22 20:27
Source code can be found here:
https://github.com/asm0dey/lostodos/tree/master/src/main/webapp

**Comment by nobitagit** [comment] 2015-03-22 23:22
You haven't declared a Doctype in the head of the document.

Add `<!DOCTYPE HTML>` as the first line of your document and see if the issue goes away.

**Comment by asm0dey** [comment] 2015-03-23 04:03
You're genius! It helped! Thank you so much!

But how did you find it?
